name: CI Pipeline

on:
  push:
    branches: 
      - main           # Trigger on pushes to 'main'
  pull_request:
    branches: 
      - main           # Trigger on pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4

      # Step 2: Log branch name
      - name: Run your build steps
        run: echo "Running on branch ${{ github.ref_name }}"
      
      # Step 3: Set a dynamic image tag
      - name: Set Image Tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mosesonwuzua/mostechimages:${{ env.IMAGE_TAG }}

      # Step 5: Scan Docker image using Trivy and generate a JSON report
      - name: Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: mosesonwuzua/mostechimages:${{ env.IMAGE_TAG }}
          format: json
          output: trivy-report.json

      # Step 6: Upload Trivy report as a build artifact
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: Trivy-Report
          path: trivy-report.json

      # Step 7: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 8: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push mosesonwuzua/mostechimages:${{ env.IMAGE_TAG }}
